// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpT8wAolhEJPn_7t-12ISfpUCfttgrKY',
    appId: '1:663591440131:web:0dc42fab0a5d3f1d532336',
    messagingSenderId: '663591440131',
    projectId: 'cm-ex-dc',
    authDomain: 'cm-ex-dc.firebaseapp.com',
    storageBucket: 'cm-ex-dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVclamps5X1lvMeVlqkw7AHHnhP9tHiE',
    appId: '1:663591440131:android:34aecc9edd477e42532336',
    messagingSenderId: '663591440131',
    projectId: 'cm-ex-dc',
    storageBucket: 'cm-ex-dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9509qAARkBGq2vTqcmfylwbgXQFm7zhM',
    appId: '1:663591440131:ios:313d14848eb526d1532336',
    messagingSenderId: '663591440131',
    projectId: 'cm-ex-dc',
    storageBucket: 'cm-ex-dc.firebasestorage.app',
    iosBundleId: 'com.example.cmExDc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9509qAARkBGq2vTqcmfylwbgXQFm7zhM',
    appId: '1:663591440131:ios:313d14848eb526d1532336',
    messagingSenderId: '663591440131',
    projectId: 'cm-ex-dc',
    storageBucket: 'cm-ex-dc.firebasestorage.app',
    iosBundleId: 'com.example.cmExDc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMpT8wAolhEJPn_7t-12ISfpUCfttgrKY',
    appId: '1:663591440131:web:696e2d92be142ec9532336',
    messagingSenderId: '663591440131',
    projectId: 'cm-ex-dc',
    authDomain: 'cm-ex-dc.firebaseapp.com',
    storageBucket: 'cm-ex-dc.firebasestorage.app',
  );
}
